### ISSUE TITLE
Doesn't work in activator

### ISSUE THREAD

**Issue by xpavlic4** [deanwampler/spark-workshop#10]
I run 
./activator new spark-workshop spark-workshop

and all I got was:

Fetching the latest list of templates...

OK, application "spark-workshop" is being created using the "spark-workshop" template.

akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://default/user/template-cache#-69972476]] after [10000 ms]
	at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:333)
	at akka.actor.Scheduler$$anon$7.run(Scheduler.scala:117)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:599)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:597)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:467)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.executeBucket$1(Scheduler.scala:419)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.nextTick(Scheduler.scala:423)
	at akka.actor.LightArrayRevolverScheduler$$anon$8.run(Scheduler.scala:375)
	at java.lang.Thread.run(Thread.java:745)

**Comment by deanwampler** [comment]
I think the timeout is too aggressive. I believe it's running the compile
and tests, which take more than 10 secs. Can you know open the project and
use it?

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com

**Comment by chicagoscala** [comment]
I think you ran into this bug:
https://github.com/typesafehub/activator/issues/728

However, I just tried creating the project myself with Activator on my iMac
(with a fast processor and plenty of memory) and it worked fine.If you
can't get the project to clone successfully so you can compile, test, and
run the examples, send me the whole log dump so I can add it to this bug.
An alternative is to just clone the project from GitHub and use it with
your favorite developer tools (what I always do...). The tutorial is in
tutorial/index.html. Good luck.

Dean Wampler, Ph.D.
Typesafe
"Functional Programming for Java Developers",
"Programming Scala", and
"Programming Hive" - all from O'Reilly
twitter: @deanwampler, @chicagoscala
http://typesafe.com
http://polyglotprogramming.com

**Comment by deanwampler** [comment]
The activator bug is now fixed, so closing.
